feat(ui-kit): add card component and stories
washingtonpost/wpds-ui-kit pull request #259
Opened 2022-11-07 16:59 UTC by clairehhelms

## What I did

Added card component and stories. Card is essentially a container with light shadow and padding, which the client may elect out of by using the css property. Card theoretically supports any nested components – below are visuals on testing this with button, text, image, and accordion. 

As far as design goes, there is no provided design. The final screenshot is the results of an audit of the current instances of Card on the website – the design here is different than what I have implemented (border instead of shadow), but I can easily change this if desired.

![Screen Shot 2022-11-07 at 11 51 13 AM](https://user-images.githubusercontent.com/67281745/200367820-6a3e2b39-e387-468d-9052-6bbf05a8103f.png)
![Screen Shot 2022-11-07 at 11 51 56 AM](https://user-images.githubusercontent.com/67281745/200367943-5f4f9d9d-a1e2-4d1e-abe3-e1ed50183366.png)
![Screen Shot 2022-11-07 at 11 52 22 AM](https://user-images.githubusercontent.co
<img width="498" alt="Screen Shot 2022-11-07 at 11 56 41 AM" src="https://user-images.githubusercontent.com/67281745/200369046-91efd97f-1caf-463f-ad52-b2dee7eaa5e1.png">
m/67281745/200368045-6f3cb917-c86f-48b1-bf48-cdac84b72111.png)

![Screen Shot 2022-11-07 at 11 52 36 AM](https://user-images.githubusercontent.com/67281745/200368112-ec7dda7e-bf83-4e2a-a7b2-2751973bf8fc.png)

2022-11-16 16:09 UTC, atomictangerine commented on ui/card/src/Card.tsx
> +      <StyledCard ref={ref} css={props.css}>
don't forget to pass in the rest of the props

2022-12-05 16:05 UTC, atomictangerine commented on build.washingtonpost.com/docs/components/card.mdx
> +  <p>TODO: add Zeplin anatomy img</p>
I'd say we take this section out if we don't have anything to put in them. We can put it back later.

2022-12-05 16:05 UTC, atomictangerine commented on build.washingtonpost.com/docs/components/card.mdx
> +// Need design input?
Maybe take this out? I know we still need design input on this docs page, but I don't think we need to explicitly put it in the doc.

2022-12-05 16:05 UTC, atomictangerine commented on build.washingtonpost.com/docs/components/card.mdx
> +Card has no props.
Not technically true. Card has the children prop at the very least

2022-12-05 16:05 UTC, atomictangerine commented on ui/card/src/Card.tsx
> +    return <StyledCard css={css} {...props}>{children}</StyledCard>;
also, don't forget to pass in ref

2022-12-14 19:28 UTC, BrianAA requested changes
Everything else looks great!

2022-12-14 19:28 UTC, BrianAA commented on ui/card/src/Card.tsx
> +  border: theme.colors.subtle,
The only feedback I have about color is that we should use the same as our divider as they serve the same purpose creating a divide between the background and surrounding content. 
`theme.colors.$faint`
https://github.com/washingtonpost/wpds-ui-kit/blob/e34732d7b0920f3d595190e3353eefdb15fb0b93/ui/divider/src/Divider.tsx#L15

2022-12-16 17:23 UTC, clairehhelms commented on ui/card/src/Card.tsx
> +  border: theme.colors.subtle,
Thank you! fixed

2022-12-19 18:13 UTC, atomictangerine approved these changes
Just the question about the import in the storybook file

2022-12-19 18:13 UTC, atomictangerine commented on ui/card/src/play.stories.jsx
> +import { AccordionTrigger } from "@radix-ui/react-accordion";
How come you're not using the wpds accordionTrigger?

2023-01-09 18:44 UTC, merged